apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-simple
  template:
    metadata:
      labels:
        app: golang-simple
    spec:
      containers:
      - name: golang-simple
        image: asia.gcr.io/project-name/golang-simple:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
